rules:
  - include:
      - owasp-top-ten
      - javascript
      - typescript
      - react
      - express
      - nodejs

paths:
  include:
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.ts"
    - "**/*.tsx"
  exclude:
    - "**/node_modules/**"
