include:
  - p/owasp-top-ten
  - p/javascript
  - p/typescript
  - p/react
  - p/express
  - p/nodejs
  - p/security-audit

rules:
  - id: a01-broken-access-control
    pattern-either:
      - pattern: $APP.use(express.static(...))
      - pattern: $APP.use('/*', ...)
    message: "A01:2021 - Broken Access Control: Potentially unsafe static file serving or route configuration"
    languages: [javascript, typescript]
    severity: WARNING

  - id: a02-cryptographic-failures
    patterns:
      - pattern-either:
          - pattern: |
              $CRYPTO.createHash("md5")
          - pattern: |
              $CRYPTO.createHash("sha1")
    message: "A02:2021 - Cryptographic Failures: Using weak hashing algorithms (md5/sha1)"
    languages: [javascript, typescript]
    severity: ERROR

  - id: a03-injection
    patterns:
      - pattern-either:
          - pattern: |
              $DB.query($QUERY, ...)
          - pattern: |
              eval(...)
          - pattern: |
              exec(...)
    message: "A03:2021 - Injection: Potential injection vulnerability detected"
    languages: [javascript, typescript]
    severity: ERROR

  - id: a04-insecure-design
    pattern: $PASSWORD == "..."
    message: "A04:2021 - Insecure Design: Hardcoded credentials detected"
    languages: [javascript, typescript]
    severity: ERROR

  - id: a05-security-misconfiguration
    patterns:
      - pattern-either:
          - pattern: "process.env.NODE_ENV === 'development'"
          - pattern: "debug: true"
    message: "A05:2021 - Security Misconfiguration: Development configuration in production code"
    languages: [javascript, typescript]
    severity: WARNING

  - id: a06-vulnerable-components
    pattern: "package.json"
    message: "A06:2021 - Vulnerable Components: Remember to check dependencies for vulnerabilities"
    languages: [javascript, typescript]
    severity: INFO

  - id: a07-authentication-failures
    pattern-either:
      - pattern: |
          $JWT.sign($PAYLOAD, $SECRET, ...)
      - pattern: |
          $BCRYPT.hash($PASSWORD, $ROUNDS < 12)
    message: "A07:2021 - Authentication Failures: Potential weak authentication mechanism"
    languages: [javascript, typescript]
    severity: ERROR

  - id: a08-software-integrity
    pattern-either:
      - pattern: |
          npm install $PACKAGE@latest
      - pattern: |
          npm i $PACKAGE@latest
    message: "A08:2021 - Software and Data Integrity Failures: Unspecified package version"
    languages: [javascript, typescript]
    severity: WARNING

  - id: a09-logging-monitoring
    pattern: |
      console.log($MSG)
    message: "A09:2021 - Security Logging and Monitoring Failures: Missing error logging"
    languages: [javascript, typescript]
    severity: INFO

  - id: a10-ssrf
    pattern: |
      fetch($URL, ...)
    message: "A10:2021 - Server-Side Request Forgery: Potential SSRF vulnerability"
    languages: [javascript, typescript]
    severity: WARNING

paths:
  include:
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.ts"
    - "**/*.tsx"
  exclude:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/*.test.*"
    - "**/*.spec.*"

options:
  max_memory_mb: 2048
  timeout: 300
  metrics: off
